### Numpy
- 데이터는 행렬로 표현
- 행렬 데이터를 빠르게 계산
- 행렬 데이터를 생성, 수정, 계산하는 패키지
- 특징
    - C, C++, 포트란으로 작성
    - 선형대수학을 빠르게 연산
        - 스칼라, 벡터, 매트릭스

In [1]:
import numpy as np

In [5]:
# 행렬 데이터 생성

arr = np.array([1, 2, 3])
arr, type(arr)

(array([1, 2, 3]), numpy.ndarray)

In [6]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# 차원, shape, size

arr2.ndim, arr2.shape, arr2.size

(2, (2, 3), 6)

In [9]:
# 행렬의 모양(shape) 변경하기

arr2.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
# 행렬 데이터의 선택

arr2[1]

array([4, 5, 6])

In [11]:
arr2[1][::-1]

array([6, 5, 4])

In [12]:
arr2[0][1]

2

In [13]:
arr2[0,1]

2

In [14]:
# 데이터 수정

arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr2[0,1] = 999

arr2

array([[  1, 999,   3],
       [  4,   5,   6]])

In [16]:
arr2[1] = 0

arr2

array([[  1, 999,   3],
       [  0,   0,   0]])

In [17]:
# 조건으로 선택

arr2 > 7

array([[False,  True, False],
       [False, False, False]])

In [18]:
arr2[arr2>7]

array([999])

In [19]:
arr2[arr2>7] = -999

arr2

array([[   1, -999,    3],
       [   0,    0,    0]])

In [22]:
# 헹랼 데이터의 생성 2

data = np.zeros((2, 3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
data.dtype

dtype('float64')

In [27]:
data2 = data.astype('int')
data2.dtype

dtype('int32')

In [29]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [30]:
# arange

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [33]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])